### PR TITLE
fix: Support unknown files

### PR DESCRIPTION
**Pull request by jbmorley**
This is a hack. I'd appreciate some feedback on better approaches.

### CODE REVIEW

**Comment by tomsci** [comment]
Well that's a brainfart on my part... recognize.lua is passing in `verbose=true` unconditionally (leading to those spurious printfs) whereas it's supposed to only be when `--verbose` is passed in on the command line (which is not intended to ever be used with `--json`). I agree that `error()` shouldn't be there either (certainly on the `--json` code path). I'll fix those.

**Comment by tomsci** [comment]
Assuming you're happy to get `{"type": "unknown"}` for completely unknown files, and `{"type": "unknown", "uid1": 1234, "uid2": 4567, "uid3": 890}` for unknown files that do appear to have a valid UID triplet?

**Comment by jbmorley** [comment]
> Assuming you're happy to get `{"type": "unknown"}` for completely unknown files, and `{"type": "unknown", "uid1": 1234, "uid2": 4567, "uid3": 890}` for unknown files that do appear to have a valid UID triplet?

That sounds reasonable? We could also just omit the `type` field entirely if it's ever unknown. I think I'm happy with either.

**Comment by jbmorley** [comment]
At least at this stage in the game, it feels like `recognize.lua` is giving us back whatever it _knows_... Perhaps that looks a bit different in the future but it seems to be the approach so far.

**Comment by tomsci** [comment]
Fixed in cd9d1f8070ef8cc829f3a7263d28a497172cf103

**Pull request closed without merging**
